version: '3.9'
services:
  backend:
    container_name: backend
    restart: always
    build: .
    ports:
      - "8080:8080"
    links:
      - rabbitmq
    networks:
      host:

  mongo:
    image: mongo:4.2
    hostname: mongo
    container_name: mongo
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_DATABASE: miniautorizador
      MONGO_INITDB_ROOT_USERNAME: miniautorizador
      MONGO_INITDB_ROOT_PASSWORD: vr2022
    volumes:
      - ./scripts/init.js:/docker-entrypoint-initdb.d/init.js:ro

networks:
  host: